### PR TITLE
Allow for multiple users

### PR DESCRIPTION
**Pull request by bryceml**
This simplifies finding the home directory so we can support non /home/*
locations.

It also installs all desktop files, executables, and icons in the users
account so they don't interfere with any other users, this allows
multiple users to potentially install on the same machine.

### CODE REVIEW

**Comment by brandleesee** [comment]
I'll be happy to merge for Manjaro. At one point I even wanted to add for Arch but because I am as yet unfamiliar with that refrained from attempting.

When we get to include Manjaro, the script's name will have to change !!

**Comment by brandleesee** [comment]
Is this ready for merging, mate?

**Comment by bryceml** [comment]
I tested it on both ubuntu desktop 20.04 and xubuntu 20.04 and it seems to work fine, so we can probably merge this.

Also, I updated https://github.com/bryceml/epsxe-snap with a message that it looks like https://github.com/ahimta/epsxe-tools is probably the best future for a snap version of epsxe.

**Comment by brandleesee** [comment]
Thank you very much Bry! Appreciated. :)

Re snap, no problem, shall refer a particular user to the other repository.

**Pull request merged**
