### PR TITLE
parameterize mirror and protocol

### PR DESCRIPTION
**Pull request by acjohnson**
`mirrors.xmission.com` is throwing `404` right now might make more sense to use `archive.ubuntu.com`

### CODE REVIEW

**Comment by brandleesee** [comment]
Am assigning this to @bryceml in view that that part of the code is his.

@bryceml Are you in agreement of this pr request, please?

**Comment by bryceml** [comment]
I used mirrors.xmission.com because it was available over https.  If we do it over http we should verify a checksum of the file we download.  Might be good to do that anyway.

**Comment by acjohnson** [comment]
I added a `sha256sum` verification if you think that will do

**Comment by brandleesee** [comment]
As long as this approach is safe in comparison to https, then I do not object to merge this.

However, I would appreciate a final go ahead from @bryceml given that I would be altering his code.

@acjohnson Hello again, Aaron, thank you for taking the time to further enhance this script, appreciated.

**Comment by bryceml** [comment]
Had a few tweaks I thought were good here: https://github.com/acjohnson/ePSXe64Ubuntu/pull/1

Let me know what you think, if you're fine with the tweaks, you can merge that pr and then I'll merge this one.

**Comment by bryceml** [comment]
also @brandleesee I hope you're ok with it, but I added a github action on that pr so it checks for things like extra spaces, lines, possible script mistakes.

looks like this once it's merged: https://github.com/bryceml/ePSXe64Ubuntu/runs/1502602964?check_suite_focus=true

**Comment by brandleesee** [comment]
Gents pr is merged.
Thank you both :) 
@bryceml @acjohnson 
If you think of anything else please patch so we keep it in line with today's standards.

**Comment by brandleesee** [comment]
I need your expertise here, please.
So I updated CHANGELOG.md and have received the following:

image

image

image

image

**Comment by brandleesee** [comment]
The change is this:

https://github.com/brandleesee/ePSXe64Ubuntu/commit/afe7ba14b7ec380bb76a3410e9b3adeafa7e9aad#annotation_667670481

**Comment by bryceml** [comment]
Screenshot_2020-12-05_17-31-11
If you click the red X at the top and click details, you should be able to navigate to something like this.

looks like there's 2 extra spaces.

**Comment by bryceml** [comment]
I just pushed a commit that fixes that.

**Comment by bryceml** [comment]
If you check it out locally, you can install pre-commit and make sure everything is good by doing

```bash
pre-commit run -a
```

while you're in the repo.

To install pre-commit on ubuntu:
```bash
sudo apt install python3-pip
sudo pip3 install pre-commit
```

**Pull request merged**
